// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: question.proto

#include "question.pb.h"
#include "question.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* QuestionService_method_names[] = {
  "/QuestionService/UnaryRequest",
};

std::unique_ptr< QuestionService::Stub> QuestionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< QuestionService::Stub> stub(new QuestionService::Stub(channel));
  return stub;
}

QuestionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_UnaryRequest_(QuestionService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status QuestionService::Stub::UnaryRequest(::grpc::ClientContext* context, const ::QuestionRequest& request, ::QuestionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UnaryRequest_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::QuestionResponse>* QuestionService::Stub::AsyncUnaryRequestRaw(::grpc::ClientContext* context, const ::QuestionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::QuestionResponse>::Create(channel_.get(), cq, rpcmethod_UnaryRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::QuestionResponse>* QuestionService::Stub::PrepareAsyncUnaryRequestRaw(::grpc::ClientContext* context, const ::QuestionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::QuestionResponse>::Create(channel_.get(), cq, rpcmethod_UnaryRequest_, context, request, false);
}

QuestionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QuestionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QuestionService::Service, ::QuestionRequest, ::QuestionResponse>(
          std::mem_fn(&QuestionService::Service::UnaryRequest), this)));
}

QuestionService::Service::~Service() {
}

::grpc::Status QuestionService::Service::UnaryRequest(::grpc::ServerContext* context, const ::QuestionRequest* request, ::QuestionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


